services:
  postgres:
    image: postgres:17
    container_name: postgres-db-cs
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_cs:/var/lib/postgresql/data
  mongodb:
    image: mongo:7.0
    container_name: mongodb-db-cs
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mydb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_cs:/data/db
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-cs
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI
      - "61613:61613" # STOMP
    command: >
      sh -c "rabbitmq-plugins enable --offline rabbitmq_stomp && rabbitmq-server"
    volumes:
      - rabbitmq_data_cs:/var/lib/rabbitmq
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-cs
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    restart: unless-stopped
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    environment:
      GRAFANA_AUTH: "${GRAFANA_AUTH}"
    volumes:
      - ./otel-collector-config.yml:/etc/otelcol-contrib/config.yaml
    depends_on:
      - jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-cs
    restart: unless-stopped
    ports:
      - "16686:16686" # Jaeger UI
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
  csapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: csapp:dev
    container_name: csapp-app-cs
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: staging
      INFISICAL_CLIENT_ID: "${INFISICAL_CLIENT_ID:-}"
      INFISICAL_CLIENT_SECRET: "${INFISICAL_CLIENT_SECRET:-}"
      INFISICAL_PROJECT_ID: "${INFISICAL_PROJECT_ID:-}"
      JAVA_TOOL_OPTIONS: -javaagent:/app/otel/opentelemetry-javaagent.jar
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
      OTEL_METRICS_EXPORTER: "otlp"
      OTEL_LOGS_EXPORTER: "otlp"
      OTEL_TRACES_EXPORTER: "otlp"
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_RESOURCE_ATTRIBUTES: "service.name=csapp,service.namespace=my-application-group,deployment.environment=development"
      OTEL_TRACES_SAMPLER: "parentbased_traceidratio"
      OTEL_TRACES_SAMPLER_ARG: "1.0"
      OTEL_JAVAAPP_ENABLED: true
    volumes:
      - ./opentelemetry-javaagent.jar:/app/otel/opentelemetry-javaagent.jar:ro
    depends_on:
      - postgres
      - mongodb
      - rabbitmq
      - otel-collector

volumes:
  postgres_data_cs:
  mongo_data_cs:
  rabbitmq_data_cs:
