server.port=8080
server.error.include-stacktrace=never

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false


logging.level.root=INFO

logging.level.org.springframework=INFO
logging.level.org.hibernate=WARN
logging.level.org.apache.catalina=INFO

logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF

logging.level.com.mycomp.csapp=INFO

spring.mvc.throw-exception-if-no-handler-found=true

spring.web.resources.add-mappings=false

server.error.include-stacktrace=never
server.error.include-message=never

springdoc.swagger-ui.enabled=false

app.infisical.environment=prod
